site_name: Introduction to Python Programming
docs_dir: docs/

repo_name: "IntroToPython"
repo_url: "https://github.com/Divy1211/IntroToPython"

nav:
  - Python:
    - What is Programming: "index.md"
    - Basic Concepts of Python:
      - Variables: "vars.md"
      - Operations: "operations.md"
      - Flow Control: "flow_control.md"
    - Object Oriented Programming:
      - Functions: "functions.md"
      - Different Types of Arguments: "arguments.md"
      - Classes and Objects: "classes_objects.md"
      - Inheritance: "inheritance.md"


markdown_extensions:
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition
  - pymdownx.caret # handling sub- and superscripts
  - pymdownx.mark # highlighting of text
  - pymdownx.tilde # strikethrough of text
  - pymdownx.keys # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#keys
  - pymdownx.tabbed # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#tabbed
  - pymdownx.details # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#details
  - pymdownx.highlight: # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.superfences # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#superfences
  - pymdownx.smartsymbols # supporting special characters like copyright symbol (c)
  - pymdownx.arithmatex: # https://squidfunk.github.io/mkdocs-material/reference/mathjax/#arithmatex
      generic: true
  - pymdownx.tasklist: # https://squidfunk.github.io/mkdocs-material/reference/lists/#tasklist
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      separator: '[\s\-\.\_]+'

extra_css:
  - style.css

theme:
  name: material
  language: en
  favicon: imgs/code.svg
  icon:
    logo: fontawesome/solid/code
  features:
    - navigation.tabs
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand
    # - navigation.sections
  palette:
    scheme: slate
    primary: red
    accent: red
  font:
    text: Roboto Slab
    code: Source Code Pro
